# Generated by Django 3.2.5 on 2021-11-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='keystone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='phrase',
            field=models.CharField(max_length=30),
        ),
    ]
